### ISSUE TITLE
Allow for customisation

### ISSUE THREAD

**Issue by brgcode** [compas-dev/compas_view2#10]
currently the functionality of the viewer is entirely predefined. it would be useful to allow users to define custom actions and menu items.

ideally this also forms the basis for switching profiles as described in #9 

one way of accomplishing this would be to have project specific `config.json` and `Controller`...

**Comment by brgcode** [comment]
to some extent this is now in place since the user can provide a custom config file and corresponding controller...

**Comment by Licini** [comment]
> to some extent this is now in place since the user can provide a custom config file and corresponding controller...
seems this is already accomplished, should we close the issue?
