### ISSUE TITLE
Collections colors

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_view2#108]
**Describe the bug**

Collections do not work with meshes

**To Reproduce**

https://github.com/compas-dev/compas_view2/blob/main/scripts/v120_collection.py

![image](https://user-images.githubusercontent.com/18013985/148652423-9a82a9d3-9616-43b6-884d-3a95461ca897.png)

Mentioned here too:
https://github.com/compas-dev/compas_view2/pull/79

I installed view2 when creating a package:
`conda create -n wood python=3.8 mpir mpfr boost-cpp eigen=3.3 cgal-cpp=5.2 pybind11 compas compas_view2 --yes `

**Comment by ZacZhangzhuo** [comment]
Inactive close. let me know if the problem remains
