### ISSUE TITLE
Robot Simulation

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas_view2#136]
# Feature Request

As a user, I want to be able to use robot inverse kinematics so that i can simulate the robot trajectory.

## Details

**Describe alternatives you've considered**

i just imported the static robot and end effector mesh to viewer

**Comment by ZacZhangzhuo** [comment]
same question in the forum: https://forum.compas-framework.org/t/viewe-a-robot-in-compas-view2/718

**Comment by ZacZhangzhuo** [comment]
Can be found at https://github.com/compas-dev/compas_view2/blob/main/scripts/v120_robot.py
