### ISSUE TITLE
delay function

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas_view2#138]
# Feature Request

As a user, I would like to add time delays, in order for me to still use the app (pan, zoom, etc) till a function is computed, without freezing.

## Details

i am not sure if that is the right way to do it but i found a `Timer` class and when i tried to use it i got `ImportError`. 
```
    viewer.status("waiting for some function ...")
    viewer.timer(1000, some_callable_def, singleshot=True)
```

```
File "c:\Users\user\.conda\envs\view2\Lib\site-packages\compas_view2\app\app.py", line 43, in <module>
    from .timer import Timer
ImportError: attempted relative import with no known parent package
```

**Comment by Licini** [comment]
Done with #141
