### ISSUE TITLE
Zoom Extents

### ISSUE THREAD

**Issue by kurt-rhee** [compas-dev/compas_view2#158]
# Feature Request

As a someone who uses a geographic projection I would like to zoom_extents for my viewer.

## Details

**Is your feature request related to a problem? Please describe.**

Right now the center of the view is at the origin, because I use a geographic projection, x and y are often very large numbers.

**Describe the solution you'd like**

I would like to zoom_extents to be able to quickly find my objects in space.

**Describe alternatives you've considered**

Is there a way to set the origin of the camera?

**Additional context**

Thank you!

**Comment by ZacZhangzhuo** [comment]
similar to #111
