### ISSUE TITLE
sceneform.py - selection of child objects

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_view2#186]
# Feature Request

@ZacZhangzhuo @Licini It would be useful to have a selection of childs when clicked on the **sceneform**.
Currently only one object is selected at a time, but it would be great to have the childs selected too.

I already tried to test different things on sceneform.py without luck.
If you could at least point me how to implement this feature, I could also try it myself.

## Details

Following is the image that describes the needed feature:
<img width="1631" alt="image" src="https://github.com/compas-dev/compas_view2/assets/18013985/0375be81-8879-4d38-a7e2-c2bd82f58463">

**Is your feature request related to a problem? Please describe.**

I think in general, sceneform could be useful with more features, that could help interact with the scene objects, e.g. giving extra methods when a tree object is right clicked.

**Comment by ZacZhangzhuo** [comment]
I think adding a `multi-selection` function might solve this problem. :) I have added a PR #189

**Comment by ZacZhangzhuo** [comment]
hi I produced this example #190 that might be helpful for you :)
