### ISSUE TITLE
Vertical lookat vector fails

### ISSUE THREAD

**Issue by tomvanmele** [compas-dev/compas_view2#209]
**Describe the bug**

If the lookat vector is vertical, the viewer failts.

**To Reproduce**

```python
viewer = App()
viewer.view.camera.position = [0, 0, 10]
viewer.view.camera.look_at([0, 0, 0])
viewer.run()
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Python version [e.g. 2.7]
- Python package manager [e.g. macports, pip, conda]

**Additional context**

**Comment by Licini** [comment]
@tomvanmele Fixed now.
