### ISSUE TITLE
ortho views zoom doesn't update

### ISSUE THREAD

**Issue by GeneKao** [compas-dev/compas_view2#24]
**Describe the bug**

While using orthogonal views (in Front, Right, and Top views) the viewer doesn't work properly. 

It feels like the scrolling is activated but the viewer doesn't update automatically. It's updated once I click other modes and switch it back. 

**Desktop (please complete the following information):**

- OS: macOS Big Sur 11.1 
- Python version: 3.8.6
- Python package manager: conda

**Comment by brgcode** [comment]
tried to fix it but was unsuccessful. @Licini ideas?
