### ISSUE TITLE
mouse selection problem

### ISSUE THREAD

**Issue by GeneKao** [compas-dev/compas_view2#29]
**Describe the bug**

@Licini The mouse selection of polyline seems has some problems. Please see the following example and screenshot. 
Whenever I select the red polyline, the black line is also highlighted, even though line selection is not implemented. Not sure why. 

**Screenshots**
<img width="912" alt="Screenshot 2021-02-03 at 11 55 02" src="https://user-images.githubusercontent.com/1162842/106737193-ac3e2680-6616-11eb-8b2c-ae4323691907.png">

**To Reproduce**
``` python 
import random

from compas.geometry import Polyline, Line
from compas_view2 import app

viewer = app.App()

pts = []
for i in range(10):
    pts.append([random.uniform(0, 10), random.uniform(0, 10), random.uniform(0, 10)])

polyline = Polyline(pts)
viewer.add(polyline)

pts = []
for i in range(5):
    pts.append([random.uniform(0, 10), random.uniform(0, 10), random.uniform(0, 10)])

polyline = Polyline(pts)
viewer.add(polyline, show_points=True, pointcolor=(0, 0, 1), linecolor=(1, 0, 0), linewidth=5)

line = Line([0, 0, 0], [-3, -3, 3])
viewer.add(line, show_points=True, linewidth=10)

viewer.show()

```

**Desktop:**

- OS: macOS Big Sur 11.1
- Python version: 3.8.6
- Python package manager: conda

**Comment by Licini** [comment]
Should be fixed now. The selection part for line object was not setup properly @GeneKao Could you try again?

**Comment by GeneKao** [comment]
it's working now :)
