### ISSUE TITLE
Possibility to customise object opacity

### ISSUE THREAD

**Issue by GeneKao** [compas-dev/compas_view2#33]
# Feature Request

Currently, we have the opacity setting in the application level: ghosted or shaded mode. 
I think it would be more convenient to use if we separate and enable this also in the object level, so it's easier to draw diagrams with different modes among different object.

**Comment by brgcode** [comment]
is this resolved?

**Comment by Licini** [comment]
> is this resolved?

Not yet, I'm working on it now

**Comment by Licini** [comment]
done
