### ISSUE TITLE
performance significantly decrease 

### ISSUE THREAD

**Issue by GeneKao** [compas-dev/compas_view2#46]
**Describe the bug**

@Licini @tomvanmele @brgcode I noticed a significant performance decrease after updating from commit e7f8073a to d09adee5. 
The camera rotation becomes pretty laggy when there is a lot of lines (I didn't test with other objects). 

**To Reproduce**

The problem can be reproduced with the following code. 

``` python 
from compas_view2 import app
from compas.geometry import Line
from random import random

viewer = app.App()

for i in range(1000):
    line = Line([random()*20, random()*20, random()*20], [random()*20, random()*20, random()*20])
    viewer.add(line, linecolor=(random(), random(), random()), linewidth=2)

viewer.show()

```

**Desktop (please complete the following information):**
- OS: macOS Big Sur 11.1
- Python version: 3.8.6
- Python package manager: conda

**Comment by brgcode** [comment]
@Licini yes i also noticed this. could it be related to the dynamic buffers? or what else has changed recently?

**Comment by Licini** [comment]
Looking at it now, it's more likely to be the matrix transforms adding lot of additional computation on simpler objects

**Comment by brgcode** [comment]
let's maybe leave that out for now then
