### ISSUE TITLE
Grid depth

### ISSUE THREAD

**Issue by brgcode** [compas-dev/compas_view2#53]
currently grid and objects interfere. would be better if grid is always in background...

**Comment by Licini** [comment]
Thought I have done that already, must be overwritten somewhere....Let me check

**Comment by brgcode** [comment]
somewhat related. perhaps it also makes sense to have a separate shader program for the model objects v. the overlays v. the texts v. ...

**Comment by Licini** [comment]
> somewhat related. perhaps it also makes sense to have a separate shader program for the model objects v. the overlays v. the texts v. ...

Closing this issue now. Will make a new issue on this topic
