### ISSUE TITLE
Separate shaders for models, overlays, text

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_view2#61]
@brgcode  for texts/sprites glsl >= v1.30 is needed for the texture sampling function, would it be possible to have shaders with different versions working at same time?

**Comment by brgcode** [comment]
i think on most machines we could use `3.30`. so far `1.20` was only necessary on parallels. in `3.30` we could use vao's...
so perhaps we check if `3.30` is available and otherwise fall back to `1.20`?

**Comment by Licini** [comment]
> i think on most machines we could use `3.30`. so far `1.20` was only necessary on parallels. in `3.30` we could use vao's...
> so perhaps we check if `3.30` is available and otherwise fall back to `1.20`?

I just found there is a `texture2D` function in 1.2 does exactly the same like `texture` , so it turned out to be just a name change....

**Comment by brgcode** [comment]
okay even better
