### ISSUE TITLE
Proper Opacity Blending

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_view2#67]
Currently the opacity blending only works in drawing order:
![image](https://user-images.githubusercontent.com/17893605/110444065-e474d100-80bc-11eb-939b-1c3c71efdca9.png)

To introduce proper blending we will need to sort the object based on camera distance.

**Comment by brgcode** [comment]
maybe we can start using a scene graph for that?

**Comment by Licini** [comment]
You mean start to having child-parent relationships on objects?

> maybe we can start using a scene graph for that?

**Comment by brgcode** [comment]
always assumed that a scene graph was used to speed up, for example, depth testing through parent-child relationships such that not all objects have to be tested...

**Comment by Licini** [comment]
> always assumed that a scene graph was used to speed up, for example, depth testing through parent-child relationships such that not all objects have to be tested...

Ah I see,  but I guess you'd still have to sort through all child objects as long as they are visible and transparent on screen. For example a Dome object which contains a loft of bricks as children. Unless we explicitly specify a node depth limit in scenario of very many objects
