### ISSUE TITLE
Docs site clean up

### ISSUE THREAD

**Issue by Licini** [compas-dev/compas_view2#69]
The clean-up workflow seems not working accordingly from time to time, with some pull request folder failed to be deleted. My guess is that when several jobs are triggered at the same time, they could sometimes overwrite each other.  I can either go ahead to fix this by making sure they are executed in right order or just implement the same strategy of not deploy pull request we just applied on compas core. Which way do you prefer? @brgcode

**Comment by brgcode** [comment]
not deploy for PR. just build the docs and check for errors...

**Comment by Licini** [comment]
> not deploy for PR. just build the docs and check for errors...

Done
