### ISSUE TITLE
OpenGL can't be loaded on Linux

### ISSUE THREAD

**Issue by brgcode** [compas-dev/compas_view2#71]
the issue is similar to the one on Mac, but the fix for Mac obviously doesn't work on Linux...

**Comment by Licini** [comment]
@brgcode It works on my linux machine, what is the os and error you got?

**Comment by brgcode** [comment]
after the package build on conda-forge the built package is imported as a test. there i get the error that OpenGL cannot be found. should it be installed separately? would have though this is taken care of by conda but that doesn't seem to be the case. the error looks similar as the one we got with the latest Mac OS versions. the solution there was to do this https://github.com/compas-dev/compas_view2/blob/main/src/compas_view2/__init__.py#L20

**Comment by Licini** [comment]
Ok let me try a bit more... I was only testing on an existing env, might have installed things manually before
