### ISSUE TITLE
Collection options not working for polylines

### ISSUE THREAD

**Issue by brgcode** [compas-dev/compas_view2#78]
Adding a collection of polylines throws an error saying that `color` is not supported...

**Comment by brgcode** [comment]
in general it is a bit annoying that one cannot use the same keyword parameters with collections as with the individual objects...

**Comment by Licini** [comment]
> in general it is a bit annoying that one cannot use the same keyword parameters with collections as with the individual objects...

Just pushed a quick fix for it to work, gonna look deeper into the setup about second comment

**Comment by petrasvestartas** [comment]
@Licini  I tried to run this example, but there are no colors for collections:

![image](https://user-images.githubusercontent.com/18013985/148028293-c7ea30b3-d575-4436-9d71-579d6d951a1a.png)
