### ISSUE TITLE
compas_view2 and pythonnet package issue

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_view2#94]
**Describe the bug**

pythonnet package with compas_view2
Error (application runs just this message is printed to console): 
`QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)" `

**To Reproduce**

`pip install pythonnet`
(I did not install pip install clr by accident)
after declaring clr without any additional code and calling compas_view2 the COM error appears in console.
The viewer runs and I can execute the code. Just this COM error is printed to console.

```

import sys
import clr #1 conda activate view2 2 pip install pythonnet

import compas.geometry as cg
from compas_view2.app import App
from compas_view2.objects import Collection

viewer = App()
viewer.add(cg.Point(0,0,0))
viewer.run()

```
Same just without the printed error.

**Desktop (please complete the following information):**

- OS: Windows
- Python version [3.8]
- Python package manager [ conda]
![image](https://user-images.githubusercontent.com/18013985/131082049-262c0bbd-b307-470b-bc0f-cf4624f42b7d.png)

**Comment by brgcode** [comment]
i don't think this has anything to do with view2...
