### ISSUE TITLE
Grid and Zoom to Object and some other beginner questions

### ISSUE THREAD

**Issue by petrasvestartas** [compas-dev/compas_view2#95]
I have a few other questions, I first of all thank you for the viewer it is really cool and helpful!

1. Is there a way to hide the default grid?
![image](https://user-images.githubusercontent.com/18013985/131157107-e7d7b14b-0464-492c-9eb9-98751e51664b.png)

2. And sometimes my geometry is not positioned close to zero by intention.  Is there a way to zoom the camera view to geometry? 

3. For displaying planar geometry likes not polygons with fills, like image below in pink color. Do I need to convert planar polylines to meshes, or there is a way to use directly polylines without conversion to mesh? 
![image](https://user-images.githubusercontent.com/18013985/131316857-2642ee8c-bcc9-4297-8553-2044ae28a0a8.png)

4. When passing a collections parameter to viewer. Is it also possible to do the same for attributes. For example, this wont work:
`viewer.add(Collection(outPolylines),color = Collection(outPolylinesColors) )`

**Comment by brgcode** [comment]
1. yes, `viewer = App(show_grid=False)`
2. unfortunately not yet
3. i noticed indeed that the polygon object doesn't support fill colors, although it should. conversion to mesh is relatively easy though `viewer.add(Mesh.from_polygons([polygon]))`
4. currently, objects in a collection always have the same coloor

**Comment by petrasvestartas** [comment]
Thank you for the help:)

**Comment by petrasvestartas** [comment]
@brgcode 

Considering the second point of zooming to certain geometry.
Currently I am using this for scaling down the input to the viewer.
In this case, do I modify original polyline or not?
In RhinoCommon I must duplicate the input polyline.

```
def DisplayPolylines(viewer, polylines, scale=0.01):
    polylinesScaled = []
    for i in polylines:
        polyline = i
        polyline.transform(cg.transformations.scale.matrix_from_scale_factors([scale,scale,scale]))
        polylinesScaled.append(polyline)
    viewer.add(Collection(polylinesScaled),color = (0, 0, 0), linewidth = 2)
```

**Comment by brgcode** [comment]
currently you are changing the original polylines.
to avoid this, use `transformed` instead of `transform`

```python
for p in polylines:
    scaled.append(p.transformed(Scale.from_factors([scale, scale, scale])))
```

**Comment by petrasvestartas** [comment]
Thank you
